name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Start SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"your_project_key" /d:sonar.host.url="http://13.126.27.18:9000" /d:sonar.login="$SONAR_TOKEN"
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="$SONAR_TOKEN"

      - name: Publish build artifacts
        run: echo "Build completed"
