name: Build, Analyze and Deploy Docker Image with Auto Increment Tag

on:
  push:
    branches:
      - main

env:
  SONAR_HOST_URL: "http://13.126.124.58:9000"
  DOCKER_IMAGE: "dharshansr/murali_lanister"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch latest tag and calculate next version
      id: get_tag
      run: |
        git fetch --tags
        latest_tag=$(git tag --sort=-v:refname | grep '^v[0-9]*$' | head -n 1)
        echo "Latest tag: $latest_tag"
        if [[ "$latest_tag" =~ ^v([0-9]+)$ ]]; then
          next_tag="v$((BASH_REMATCH[1]+1))"
        else
          next_tag="v1"
        fi
        echo "NEXT_TAG=$next_tag" >> $GITHUB_ENV
        echo "Next Docker tag will be: $next_tag"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: SonarQube Begin Analysis
      run: dotnet sonarscanner begin /k:"dotnet-webapp" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"

    - name: Build Project
      run: dotnet build --no-restore

    - name: SonarQube End Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ env.NEXT_TAG }}

    - name: Create Git Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag ${{ env.NEXT_TAG }}
        git push origin ${{ env.NEXT_TAG }}
