name: Build, Analyze and Deploy Docker Image with Auto Increment Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  SONAR_HOST_URL: "http://13.126.124.58:9000"
  DOCKER_IMAGE: "dharshansr/murali_lanister"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: SonarQube Begin Analysis
      run: dotnet sonarscanner begin /k:"dotnet-webapp" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}"

    - name: Build Project
      run: dotnet build --no-restore

    - name: SonarQube End Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Fetch all tags
      run: git fetch --tags

    - name: Get next image version tag
      id: get_tag
      run: |
        TAG_PREFIX="v"
        LAST_TAG=$(git tag --sort=-v:refname | head -n 1)
        if [[ "$LAST_TAG" =~ ^v([0-9]+)$ ]]; then
          NEXT_TAG="${TAG_PREFIX}$((${BASH_REMATCH[1]} + 1))"
        else
          NEXT_TAG="${TAG_PREFIX}1"
        fi
        echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
        echo "Docker image will be tagged as $NEXT_TAG"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ env.NEXT_TAG }}

    - name: Create Git Tag and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $NEXT_TAG
        git push origin $NEXT_TAG

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 13.126.124.58
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull dharshansr/murali_lanister:latest
          docker stop murali || true && docker rm murali || true
          docker run -d -p 70:80 --name murali dharshansr/murali_lanister:latest
